import {
  milestones,
  lives,
  serenade,
  dkGifts,
  liveImages,
  photoAlbums,
  covers,
  milestoneThumbs,
} from '../data/index.js'

export function initArchive() {
history.scrollRestoration='manual';
if(location.hash||location.search)history.replaceState(null,'',location.pathname);
window.scrollTo(0,0);
addEventListener('pageshow',()=>requestAnimationFrame(()=>window.scrollTo(0,0)),{once:true});
const content=document.querySelector('#content');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const source=(url,label='查看來源 · View source')=>`<a class="source" href="${safe(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
const membershipCover=r=>!/^\d{4}-\d{2}-\d{2}$/.test(r[0])||/會員|membership|CH\+/i.test(r[1]+' '+r[2]+' '+r[4]);
const bilingualTag=tag=>({
 '回歸歌曲':'回歸歌曲 · COMEBACK','合作單曲':'合作單曲 · COLLABORATION','合作歌曲':'合作歌曲 · COLLABORATION','日文作品':'日文作品 · JAPANESE RELEASE','小分隊':'小分隊 · UNIT','夫碩順':'夫碩順 · BSS','個人歌曲':'個人歌曲 · SOLO','個人作品':'個人作品 · SOLO','原聲帶':'原聲帶 · OST','音樂劇':'音樂劇 · MUSICAL','綜藝節目':'綜藝節目 · VARIETY SHOW','固定綜藝':'固定綜藝 · REGULAR CAST','綜藝／舞台':'綜藝／舞台 · SHOW / STAGE','打歌舞台':'打歌舞台 · MUSIC SHOW','大型舞台':'大型舞台 · FESTIVAL STAGE','商業活動':'商業活動 · CAMPAIGN','重要歷程':'重要歷程 · MILESTONE','節目／合作舞台':'節目／合作舞台 · SHOW / COLLAB','合作／回歸':'合作／回歸 · COLLAB / COMEBACK','翻唱作品':'翻唱作品 · COVER',
 '個人直播':'個人直播 · SOLO LIVE','個人／語音直播':'個人／語音直播 · SOLO / VOICE LIVE','DK 直播／官方帳號':'DK 直播／官方帳號 · DK LIVE / OFFICIAL ARCHIVE','生日／共同直播':'生日／共同直播 · BIRTHDAY / GROUP LIVE','官方回歸直播':'官方回歸直播 · COMEBACK LIVE','官方節目直播':'官方節目直播 · OFFICIAL PROGRAM LIVE','早期回放／共同直播':'早期回放／共同直播 · ARCHIVE / GROUP LIVE','V LIVE 歷史回放':'V LIVE 歷史回放 · ARCHIVE','CH+ 歷史回放':'CH+ 歷史回放 · ARCHIVE','歷史回放':'歷史回放 · ARCHIVE','歷史合播':'歷史合播 · GROUP ARCHIVE','歷史電台':'歷史電台 · RADIO ARCHIVE','早期回放':'早期回放 · ARCHIVE','個人直播／歷史回放':'個人直播／歷史回放 · SOLO ARCHIVE'
 }[tag]||tag);
milestones.forEach(r=>r[1]=bilingualTag(r[1]));
lives.forEach(r=>r[4]=bilingualTag(r[4]));
const fanCopy={
 zh:['鈴蘭，是春天捎來的第一封信，花語是「幸福歸來（Return of Happiness）」。','我們將思念種進時光，以 18 個盛放前的片刻，細細倒數春天的來臨。每一張手幅，都是鈴蘭悄然生長的一個階段，也是我們將思念化作期待的印記。','直到鈴蘭盛放，幸福如約歸來；而我們，也終將在花開之日，再次相見。'],
 en:['Lily of the valley is the first letter spring sends us. In the language of flowers, it means “the return of happiness.”','We plant our longing in time, counting down to spring through 18 moments before the flowers bloom. Each banner marks a quiet stage in the growth of lily of the valley—a keepsake of longing becoming hope.','When the lilies bloom, happiness will return as promised. And on that day, we will meet again.'],
 ko:['은방울꽃은 봄이 보내오는 첫 번째 편지입니다. 꽃말은 “다시 찾은 행복(Return of Happiness)”입니다.','우리는 그리움을 시간 속에 심고, 꽃이 피기 전의 열여덟 순간을 지나며 봄이 오기를 기다립니다. 한 장 한 장의 슬로건은 은방울꽃이 조용히 자라나는 한 단계이자, 그리움을 설렘으로 바꾸어 온 우리의 흔적입니다.','은방울꽃이 활짝 피면 행복도 약속처럼 돌아오겠지요. 그리고 꽃이 피는 그날, 우리도 다시 만나게 될 거예요.']
};
let fanLanguage='zh';
function fanParagraphs(){return fanCopy[fanLanguage].map(t=>`<p>${safe(t)}</p>`).join('');}
function render(){
 if(observer)observer.disconnect();
 const page=['milestones','live','photos','covers','banners','serenade','gifts'].includes(location.hash.slice(1))?location.hash.slice(1):'milestones';
 document.body.classList.toggle('is-banner-page',page==='banners');
 document.querySelectorAll('.archive-tabs a').forEach(a=>{const active=a.hash==='#'+page;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
 if(page==='milestones'||page==='serenade'){
 const records=page==='serenade'?serenade:milestones;
 const groups={};[...records].sort((a,b)=>b[0].localeCompare(a[0])).forEach(r=>(groups[r[0].slice(0,4)]??=[]).push(r));
 const titleFilms=[['Fighting','mBXBOLG06Wc'],['Super','-GQg25oP0S4'],['God of Music','zSQ48zyWZrY'],['MAESTRO','ThI0pBAbFnk'],['LOVE, MONEY, FAME','5NPe8_gDSr4'],['Darl+ing','bTtNV6hgDno'],['_WORLD','VCDWg0ljbFQ'],['Ready to love','yCvSR4lSqTg'],['Not Alone','0n8su37VyZQ'],['Left & Right','HdZdxocqzq4'],['Fallin','u4iDL3c0T1c'],['Fear','ap14O5-G7UA'],['HIT','F9CrRG6j2SM'],['Oh My','_5PELxP8Udg'],['THANKS','gZItyr1SNjU'],['CLAP','CyzEtbG-sxY'],['Don’t Wanna Cry','zEkg4GBQumc'],['BOOMBOOM','CNEeAaH3bFc'],['VERY NICE','J-wFp43XOrA'],['Pretty U','J5juKw-mnGw'],['MANSAE','9M7k9ZV67c0'],['Adore U','9rUFQJrCT7M']];
 content.innerHTML=`${page==='serenade'?'<div class="serenade-intro"><span class="eyebrow">DxS / DK X SEUNGKWAN</span><h2>小夜曲 · Serenade</h2><p>Ordinary Notes 全 6 集與 Bonus Book，以及《小夜曲》ON STAGE 的 Inside Seventeen 幕後紀錄。</p></div>':''}<div class="milestone-layout"><div class="milestone-list">${Object.keys(groups).sort().reverse().map((y,i)=>`${page==='milestones'?`<details class="year-group year-fold" open><summary class="year-label"><span>${y}</span><span class="year-count">${groups[y].length} 筆紀錄</span><span class="year-action"></span></summary>`:`<section class="year-group"><h3 class="year-label">${y}</h3>`}<div>${groups[y].map(r=>{const linked=(r[4].match(/(?:youtu\.be\/|youtube\.com\/watch\?[^#]*v=)([\w-]{11})/)||[])[1],matched=titleFilms.find(x=>r[2].includes(x[0])),id=linked||(matched&&matched[1]),thumb=r[5]||(typeof milestoneThumbs!=='undefined'&&milestoneThumbs[r[2]])||(id?'https://i.ytimg.com/vi/'+id+'/hqdefault.jpg':''),preview=thumb?`<span class="record-preview" aria-hidden="true"><img src="${safe(thumb)}" alt="${safe(r[2])} 對應影像縮圖" loading="lazy" referrerpolicy="no-referrer"></span>`:'';return `<article class="record"><time class="date" datetime="${safe(r[0])}">${r[0].length>4?r[0].slice(5).replace('-',' / '):'年度紀錄'}</time><div class="record-copy"><span class="tag">${safe(r[1])}</span><h3>${safe(r[2])}</h3><p>${safe(r[3])}</p></div>${preview}${source(r[4],page==='serenade'?(r[4].includes('weverse.io')?'觀看 Weverse · Watch':'觀看 YouTube · Watch'):'查看來源 · View source')}</article>`}).join('')}</div>${page==='milestones'?'</details>':'</section>'}`).join('')}</div></div>`;

 }else if(page==='live'){
 content.innerHTML=`<div class="live-grid">${lives.map(r=>`<article class="live-card"><a class="live-art ${membershipCover(r)?'membership-cover':liveImages[r[3]]?'':'image-unavailable'}" href="https://weverse.io/seventeen/live/${r[3]}" target="_blank" rel="noopener noreferrer" aria-label="觀看 ${safe(r[1])}"><span class="membership-label">${membershipCover(r)?'weverse membership':''}</span><span class="live-image-note">${liveImages[r[3]]?'縮圖暫時無法載入 · 點此觀看回放':'暫無可確認的縮圖 · 點此觀看回放'}</span>${!membershipCover(r)&&liveImages[r[3]]?`<img src="${safe(liveImages[r[3]])}" alt="${safe(r[1])} 官方直播縮圖" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.hidden=true;this.parentElement.classList.add('image-unavailable')">`:""}<span class="live-date">${r[0]?r[0].replaceAll('-','.'):'日期待確認'}</span><span class="play" aria-hidden="true">▷</span></a><span class="tag">${safe(r[4])} / ${r[0]||'日期待確認'}</span><h3>${safe(r[1])}</h3><p>${safe(r[2])}</p>${source('https://weverse.io/seventeen/live/'+r[3],'前往 Weverse 回放 · Watch on Weverse')}</article>`).join('')}</div>`;
 }else if(page==='gifts'){
 content.innerHTML=`<section class="gifts-intro"><span class="eyebrow">ON THE 18TH · 매월 18일</span><h2>DK TIME</h2><p>每個月 18 號，收藏碩珉送來的小禮物。</p></section><div class="live-grid gift-grid">${dkGifts.map(r=>`<article class="live-card"><a class="live-art ${r.thumb?'':'image-unavailable'}" href="${safe(r.url)}" target="_blank" rel="noopener noreferrer" aria-label="查看 ${safe(r.title)}">${r.thumb?`<img src="${safe(r.thumb)}" alt="${safe(r.title)}" loading="lazy">`:'<span class="live-image-note">碩珉的禮物 · Gifts from DK</span>'}<span class="live-date">${safe(r.date.replaceAll('-','.'))}</span><span class="play" aria-hidden="true">▷</span></a><span class="tag">DK TIME / ${safe(r.date)}</span><h3>${safe(r.title)}</h3><p>${safe(r.description||'')}</p>${source(r.url,'查看禮物 · View gift')}</article>`).join('')}</div>${dkGifts.length?'':'<p class="gifts-empty">小禮物整理中。<br><span lang="en">A little collection, coming soon.</span><br><span lang="ko">작은 선물들을 모으고 있어요.</span></p>'}`;
 }else if(page==='photos'){
 const photoItems=photoAlbums.flatMap((a,album)=>a.images.map((image,index)=>({a,album,index,image})));
 const photoPage=Math.max(1,Number(new URLSearchParams(location.search).get('photo')||1));
 const pageCount=Math.max(1,Math.ceil(photoItems.length/40));
 const visiblePhotos=photoItems.slice((photoPage-1)*40,photoPage*40);
 content.innerHTML=`<div class="photo-editorial">${visiblePhotos.map((r,i)=>`<article class="photo-tile reveal tile-${i%5}"><button class="photo-open" data-album="${r.album}" data-image="${r.index}" aria-label="放大照片 · Enlarge ${safe(r.a.title)}"><img class="photo-preview" src="${safe(r.image)}" alt="${safe(r.a.title)}" loading="lazy" referrerpolicy="no-referrer"><span class="photo-sequence">${String((photoPage-1)*40+i+1).padStart(3,'0')}</span></button><div class="photo-caption"><span>${safe(r.a.date.replaceAll('-','.'))}</span><strong>${safe(r.a.title)}</strong></div></article>`).join('')}</div><nav class="photo-pages" aria-label="照片分頁 · Photo pages">${Array.from({length:pageCount},(_,i)=>`<a class="${i+1===photoPage?'active':''}" data-photo-page="${i+1}" href="#photos">${String(i+1).padStart(2,'0')}</a>`).join('')}</nav><nav class="social-directory" aria-label="官方照片來源 · Official photo sources"><span>查看原始紀錄 · ORIGINAL ARCHIVE</span><a href="https://www.instagram.com/dk_is_dokyeom/" target="_blank" rel="noopener">DK 個人帳號 · INSTAGRAM <b>↗</b></a><a href="https://www.instagram.com/saythename_17/" target="_blank" rel="noopener">SEVENTEEN 官方 · INSTAGRAM <b>↗</b></a><a href="https://x.com/pledis_17" target="_blank" rel="noopener">SEVENTEEN 官方 · X / TWITTER <b>↗</b></a></nav>`;
 content.querySelectorAll('[data-album]').forEach(b=>b.addEventListener('click',()=>openAlbum(+b.dataset.album,+b.dataset.image)));
 content.querySelectorAll('[data-photo-page]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const url=new URL(location.href);url.searchParams.set('photo',a.dataset.photoPage);url.hash='photos';history.replaceState(null,'',url);render();document.querySelector('.section-heading').scrollIntoView({block:'start'});}));

 }else if(page==='covers'){
 content.innerHTML=`<div class="cover-grid">${covers.map(r=>{const url=r.url||'https://www.youtube.com/watch?v='+r.videoId,thumb=r.thumb||(r.videoId?'https://i.ytimg.com/vi/'+r.videoId+'/hqdefault.jpg':'/assets/project-riso.png');return `<article class="cover-card reveal"><a class="cover-art" href="${safe(url)}" target="_blank" rel="noopener noreferrer"><img src="${safe(thumb)}" alt="${safe(r.title)} 翻唱影片縮圖" loading="lazy"></a><span class="tag">翻唱 · COVER / ${r.date}</span><h3>${safe(r.title)}</h3><p>原唱 · Original · ${safe(r.original)}</p>${source(url,'觀看 YouTube · Watch')}</article>`}).join('')}</div>`;
 }else{
 content.innerHTML=`<div class="fan-layout"><section class="project-intro"><span class="eyebrow">UNTIL THE LILIES BLOOM | 鈴音知春</span><h2>LOVE BY DK'S FANS</h2><div class="language-switch" role="group" aria-label="敘述語言 · Description language"><button type="button" data-lang="zh" class="arrow-cta" aria-pressed="${fanLanguage==='zh'}">中文</button><button type="button" data-lang="en" class="arrow-cta" aria-pressed="${fanLanguage==='en'}">English</button><button type="button" data-lang="ko" class="arrow-cta" aria-pressed="${fanLanguage==='ko'}">한국어</button></div><div class="fan-description" lang="${fanLanguage==='zh'?'zh-Hant':fanLanguage}" aria-live="polite">${fanParagraphs()}</div></section><div class="folder-deck" aria-label="兼粉們的愛 · 資料夾">${['white','grey','blue'].map((color,i)=>`<div class="folder-step"><button class="folder-card folder-${color}" data-folder="${i}" aria-label="開啟資料夾 ${String(i+1).padStart(2,'0')}"><span class="folder-tab">${String(i+1).padStart(2,'0')}</span><span class="folder-caption">LOVE BY DK'S FANS</span><strong>資料夾 ${String(i+1).padStart(2,'0')}</strong><span class="folder-open">OPEN ↗</span></button></div>`).join('')}</div></div><dialog class="folder-page" aria-label="資料夾內頁"><button class="folder-close arrow-cta" type="button">返回 · Back</button><span class="eyebrow">LOVE BY DK'S FANS</span><h2></h2><div class="folder-blank"></div></dialog>`;
 content.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{if(fanLanguage===button.dataset.lang)return;fanLanguage=button.dataset.lang;const box=content.querySelector('.fan-description');box.lang=fanLanguage==='zh'?'zh-Hant':fanLanguage;box.innerHTML=fanParagraphs();content.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));window.dispatchEvent(new Event('archive-rendered'));if(!reduced.matches)box.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:400,easing:'ease-out'});}));
 const folderPage=content.querySelector('.folder-page');let folderTrigger;
 content.querySelectorAll('[data-folder]').forEach(button=>button.addEventListener('click',()=>{folderTrigger=button;folderPage.querySelector('h2').className='';folderPage.querySelector('h2').textContent='資料夾 '+String(+button.dataset.folder+1).padStart(2,'0');folderPage.dataset.color=button.classList.contains('folder-blue')?'blue':button.classList.contains('folder-grey')?'grey':'white';folderPage.showModal();window.dispatchEvent(new Event('archive-rendered'));}));
 content.querySelector('.folder-close').addEventListener('click',()=>folderPage.close());folderPage.addEventListener('close',()=>folderTrigger?.focus());

 }
 observeReveals();
 window.dispatchEvent(new Event('archive-rendered'));
}
const countdownTarget=Date.parse('2028-03-07T12:00:00+08:00');
function countdown(){const total=Math.max(0,Math.floor((countdownTarget-Date.now())/1000));const values={days:Math.floor(total/86400),hours:Math.floor(total/3600)%24,minutes:Math.floor(total/60)%60,seconds:total%60};for(const [id,value] of Object.entries(values)){const el=document.getElementById(id),next=id==='days'?String(value):String(value).padStart(2,'0');if(el.textContent!==next){el.textContent=next;if(!reduced.matches&&el.animate)el.animate([{opacity:.45,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'ease-out'});}}}
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
let observer;
function observeReveals(){if(reduced.matches || !('IntersectionObserver' in window))return;document.documentElement.classList.add('motion');observer??=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.05});document.querySelectorAll('.reveal:not(.is-visible)').forEach(el=>observer.observe(el));}
const viewer=document.querySelector('#photo-viewer');let albumIndex=0,imageIndex=0;
function showPhoto(){const a=photoAlbums[albumIndex],img=viewer.querySelector('.viewer-image img');img.src=a.images[imageIndex];img.alt=a.title+' · '+(imageIndex+1);img.referrerPolicy='no-referrer';viewer.querySelector('.viewer-info h2').textContent=a.title;viewer.querySelector('.viewer-info p').textContent=a.date+' / '+a.description;viewer.querySelector('.source').href=a.url;viewer.querySelector('.position').textContent=(imageIndex+1)+' / '+a.images.length;viewer.querySelector('.prev').disabled=imageIndex===0;viewer.querySelector('.next').disabled=imageIndex===a.images.length-1;}
function openAlbum(i,start=0){albumIndex=i;imageIndex=start;showPhoto();viewer.showModal();}
viewer.querySelector('.viewer-close').addEventListener('click',()=>viewer.close());viewer.querySelector('.prev').addEventListener('click',()=>{if(imageIndex>0){imageIndex--;showPhoto()}});viewer.querySelector('.next').addEventListener('click',()=>{if(imageIndex<photoAlbums[albumIndex].images.length-1){imageIndex++;showPhoto()}});viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});viewer.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')viewer.querySelector('.prev').click();if(e.key==='ArrowRight')viewer.querySelector('.next').click()});
let ticking=false;function scrollMotion(){const y=window.scrollY,h=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.transform='scaleX('+Math.min(1,y/Math.max(1,h))+')';ticking=false;}window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(scrollMotion);ticking=true}},{passive:true});scrollMotion();
window.addEventListener('hashchange',()=>{render();if(['#milestones','#live','#photos','#covers','#banners','#serenade','#gifts'].includes(location.hash))document.querySelector('#archive').scrollIntoView()});render();countdown();setInterval(countdown,1000);

const film=document.querySelector('#background-film'),filmButton=document.querySelector('#film-toggle');let filmPaused=reduced.matches;
let filmDuration=0,filmLooping=false;
window.addEventListener('message',event=>{if(!String(event.origin).includes('youtube'))return;try{const data=typeof event.data==='string'?JSON.parse(event.data):event.data;if(data?.event==='infoDelivery'){if(data.info?.playerState===1 || data.info?.currentTime>4)film.classList.add('film-ready');if(Number.isFinite(data.info?.duration))filmDuration=data.info.duration;const t=data.info?.currentTime;if(filmDuration&&Number.isFinite(t)&&t>=filmDuration-4&&!filmLooping){filmLooping=true;film.parentElement.classList.add('is-looping');film.contentWindow?.postMessage(JSON.stringify({event:'command',func:'seekTo',args:[4,true]}),'https://www.youtube-nocookie.com');setTimeout(()=>{film.parentElement.classList.remove('is-looping');filmLooping=false},650)}}}catch{}});
film.addEventListener('load',()=>{film.contentWindow?.postMessage(JSON.stringify({event:'listening',id:'background-film'}),'https://www.youtube-nocookie.com');film.contentWindow?.postMessage(JSON.stringify({event:'command',func:'seekTo',args:[4,true]}),'https://www.youtube-nocookie.com')});
function toggleFilm(){filmPaused=!filmPaused;if(!film.src&&!filmPaused){film.src=film.dataset.src}else{film.contentWindow?.postMessage(JSON.stringify({event:'command',func:filmPaused?'pauseVideo':'playVideo',args:[]}),'https://www.youtube-nocookie.com')}filmButton.textContent=filmPaused?'播放背景 · Play':'暫停背景 · Pause';filmButton.setAttribute('aria-pressed',String(filmPaused))}
if(!reduced.matches)film.src=film.dataset.src;else filmButton.textContent='播放背景 · Play';filmButton.setAttribute('aria-pressed',String(filmPaused));filmButton.addEventListener('click',toggleFilm);

}
